baseURL = "https://gvrkiran.github.io/blog/"
languageCode = "en-us"
title = "Abstruse Idiot"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
