baseURL = 'https://gvrkiran.github.io/blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'
# Add these lines
canonifyURLs = true

# Add a proper homepage
[params]
  mainSections = ["posts"]
