baseURL = "https://gvrkiran.github.io/blog/"
languageCode = "en-us"
title = "My Blog"
theme = "PaperMod"

# Add these for proper asset handling
publishDir = "public"
relativeURLs = true
canonifyURLs = true
uglyURLs = false

[params]
  # Basic PaperMod configs
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
