baseURL = 'https://gvrkiran.github.io/blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'

[params]
    mainSections = ["posts"]
    defaultTheme = "auto"
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
